name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install OS deps
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip git \
            python3 python3-pip python3-setuptools \
            libffi-dev libssl-dev liblzma-dev libncurses6

      - name: Install Python deps
        run: |
          set -eux
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade \
            Cython==0.29.36 \
            buildozer \
            python-for-android \
            virtualenv sh

      - name: Install Android cmdline-tools
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -eux
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
          cd "${ANDROID_SDK_ROOT}/cmdline-tools"
          curl -fsSL -o cmdline-tools.zip \
            https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip -d .
          mv cmdline-tools latest
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> "$GITHUB_ENV"
          echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "${ANDROID_SDK_ROOT}/platform-tools" >> "$GITHUB_PATH"

      - name: Accept Android licenses & install packages
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -eux
          yes | sdkmanager --licenses
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;36.1.0"

      # ★ ここを追加：Buildozer が参照する場所に SDK をリンク
      - name: Link SDK for Buildozer
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -eux
          mkdir -p "${HOME}/.buildozer/android/platform"
          rm -rf "${HOME}/.buildozer/android/platform/android-sdk" || true
          ln -s "${ANDROID_SDK_ROOT}" "${HOME}/.buildozer/android/platform/android-sdk"
          # aidl があるかチェック（無ければ失敗させて原因を早期に出す）
          test -x "${HOME}/.buildozer/android/platform/android-sdk/build-tools/36.1.0/aidl"

      - name: Configure Buildozer env
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -eux
          echo "ANDROIDSDK=${ANDROID_SDK_ROOT}" >> "$GITHUB_ENV"
          echo "ANDROIDNDK=${ANDROID_SDK_ROOT}/ndk" >> "$GITHUB_ENV"
          echo "ANDROIDAPI=34" >> "$GITHUB_ENV"
          echo "NDKAPI=23" >> "$GITHUB_ENV"
          sdkmanager --list | head -n 50 || true

      - name: Build APK
        env:
          P4A_NO_DEPS_CHECK: "1"
          PYTHONFORANDROID_NO_DEPS_CHECK: "1"
        run: |
          set -eux
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-tagger-apk
          path: bin/*.apk
