name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/36.0.0:${{ env.PATH }}

    steps:
      - uses: actions/checkout@v4

      # Linux 側の基本ツール（過去エラーを全部潰す）
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git python3 python3-pip python3-venv \
            openjdk-17-jdk-headless unzip wget zip \
            zlib1g-dev libffi-dev libssl-dev pkg-config

      # Android SDK（安定手順）+ ライセンス自動受諾 + build-tools / platform
      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp/
          mv /tmp/cmdline-tools "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;36.0.0" \
            "ndk;26.3.11579264"
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --list | head -n 50

      # Python環境 & Buildozer（過去「command not found」対策）
      - name: Install Buildozer & p4a
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --upgrade Cython buildozer \
            git+https://github.com/kivy/python-for-android.git

      # Buildozer が参照する SDK/NDK を明示
      - name: Configure Buildozer env
        run: |
          echo "ANDROIDSDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROIDNDK=$ANDROID_SDK_ROOT/ndk/26.3.11579264" >> $GITHUB_ENV
          echo "ANDROIDAPI=33" >> $GITHUB_ENV
          echo "NDKAPI=21" >> $GITHUB_ENV

      # ビルド（aidl 未検出などのハマりを回避するため verbose+依存チェックスキップ）
      - name: Build with Buildozer
        env:
          P4A_NO_DEPS_CHECK: "1"
          PYTHONFORANDROID_NO_DEPS_CHECK: "1"
        run: |
          buildozer -v android debug -- --skip-dependency-check

      # 生成 APK を成果物にアップロード（最新版 v4）
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-tagger-apk
          path: bin/*.apk
