name: Build Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip wget zip
          pip install --upgrade pip
          pip install buildozer Cython virtualenv
          # Buildozer を /usr/local/bin にリンク
          sudo ln -sf $(python3 -m site --user-base)/bin/buildozer /usr/local/bin/buildozer || true

      - name: Install Android SDK and accept licenses
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"

          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --licenses || true
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" "platforms;android-33" "build-tools;36.1.0" || true

          mkdir -p "$HOME/.buildozer/android/platform"
          if [ ! -e "$HOME/.buildozer/android/platform/android-sdk" ]; then
            ln -s "$ANDROID_SDK_ROOT" "$HOME/.buildozer/android/platform/android-sdk"
          fi

      - name: Build with Buildozer
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          PATH: /usr/local/bin:${{ github.workspace }}/android-sdk/build-tools/36.1.0:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ env.PATH }}
        run: |
          set -eux
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-tagger-apk
          path: bin/*.apk
