name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install base packages
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3 python3-pip \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev \
            libfreetype6-dev liblcms2-dev libtiff5-dev

      - name: Install Buildozer & Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build APK
        run: |
          buildozer -v android debug
