# SDKを毎回クリーンに
- name: Clean old SDK
  run: |
    set -eux
    rm -rf "${ANDROID_SDK_ROOT}"
    mkdir -p "${ANDROID_SDK_ROOT}"

# cmdline-tools 配備（tools を latest へ“丸ごと”リンク）
- name: Install Android cmdline-tools
  run: |
    set -eux
    mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
    cd "${ANDROID_SDK_ROOT}/cmdline-tools"
    curl -fsSL -o cmdline-tools.zip \
      https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    unzip -q cmdline-tools.zip && rm -f cmdline-tools.zip
    mv cmdline-tools latest
    # ★ ここが肝：tools/bin ではなく tools -> latest にリンク（lib も参照できる）
    ln -sfn "${ANDROID_SDK_ROOT}/cmdline-tools/latest" "${ANDROID_SDK_ROOT}/tools"

# Buildozer が必ずこのSDKを見るように強制リンク
- name: Link SDK for Buildozer (compat) & PATH
  run: |
    set -eux
    echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
    echo "${ANDROID_SDK_ROOT}/platform-tools"          >> $GITHUB_PATH
    mkdir -p "$HOME/.buildozer/android/platform"
    # ★ 壊れた自前SDKを消す → 今回のSDKへリンク
    rm -rf  "$HOME/.buildozer/android/platform/android-sdk"
    ln -sfn "${ANDROID_SDK_ROOT}" "$HOME/.buildozer/android/platform/android-sdk"

# sdkmanager の健全性チェック → パッケージ導入
- name: Accept Android licenses & install packages
  run: |
    set -eux
    "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --version
    yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses
    "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --install \
      "platform-tools" \
      "build-tools;36.1.0" \
      "platforms;android-33" \
      "ndk;25.1.8937393"
