name: Build Android APK

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME:     ${{ github.workspace }}/android-sdk
      P4A_NO_DEPS_CHECK: "1"
      PYTHONFORANDROID_NO_DEPS_CHECK: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- 既存ワークスペース内の残骸を可能な限り除去（SDK/NDK/Buildozerの古いもの）
      - name: Hard clean previous Android env
        run: |
          set -eux
          rm -rf "${ANDROID_SDK_ROOT}"
          rm -rf "$HOME/.buildozer/android/platform/android-sdk" || true
          rm -rf "$HOME/.buildozer/android/platform/android-ndk-*" || true
          # p4aのローカルキャッシュも消す（完全クリーン）
          rm -rf "$HOME/.python-for-android" || true

      # ---- OS 依存パッケージ（★libffiのautotools不足を解消）
      - name: Install OS deps
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip git curl make \
            python3 python3-pip python3-setuptools \
            libffi-dev libssl-dev liblzma-dev \
            autoconf automake libtool pkg-config

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ---- Python / buildozer
      - name: Install Python deps
        run: |
          set -eux
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install "Cython==0.29.36" buildozer python-for-android virtualenv sh

      # ---- Android cmdline-tools（毎回クリーン配備）※ tools 丸ごとリンク
      - name: Install Android cmdline-tools
        run: |
          set -eux
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
          cd "${ANDROID_SDK_ROOT}/cmdline-tools"
          curl -fsSL -o cmdline-tools.zip \
            https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip && rm -f cmdline-tools.zip
          mv cmdline-tools latest
          # ★ bin だけでなく tools ディレクトリ“ごと” latest へリンク（ClassNotFound対策）
          ln -sfn "${ANDROID_SDK_ROOT}/cmdline-tools/latest" "${ANDROID_SDK_ROOT}/tools"

      # ---- Buildozer が必ずこの SDK を使うよう、既定パスを強制リンク
      - name: Link SDK for Buildozer (compat) & PATH
        run: |
          set -eux
          echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/platform-tools"          >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/build-tools/36.1.0"      >> $GITHUB_PATH
          mkdir -p "$HOME/.buildozer/android/platform"
          rm -rf  "$HOME/.buildozer/android/platform/android-sdk"
          ln -sfn "${ANDROID_SDK_ROOT}" "$HOME/.buildozer/android/platform/android-sdk"

      # ---- SDK/NDK を新規導入（フルパスで呼んで健全性も確認）
      - name: Accept Android licenses & install packages
        run: |
          set -eux
          SDKM="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          "${SDKM}" --version
          yes | "${SDKM}" --licenses
          "${SDKM}" --install \
            "platform-tools" \
            "build-tools;36.1.0" \
            "platforms;android-33" \
            "ndk;25.1.8937393"
          {
            echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.1.8937393"
            echo "ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/25.1.8937393"
            echo "ANDROIDSDK=${ANDROID_SDK_ROOT}"
            echo "ANDROIDNDK=${ANDROID_SDK_ROOT}/ndk/25.1.8937393"
            echo "ANDROIDAPI=33"
            echo "NDKAPI=21"
          } >> "$GITHUB_ENV"

      # ---- 逐次フラッシュでログ欠落防止
      - name: Build APK
        run: |
          set -eux
          stdbuf -oL -eL buildozer -v android debug 2>&1 | tee buildozer.console.log

      # ---- APK（どこに出ても拾えるよう広めに）
      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            bin/*.apk
            .buildozer/android/platform/**/dists/*/bin/*.apk
            .buildozer/android/platform/**/dists/*/*.apk
          if-no-files-found: warn
          retention-days: 14

      # ---- ログは常に保存
      - name: Upload build logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            buildozer.console.log
            ./.buildozer/buildozer.log
            ./.buildozer/**/buildozer.log
            ./.buildozer/android/platform/**/dists/*/build/*.log
            ./.buildozer/android/platform/**/dists/*/build-*.txt
          if-no-files-found: warn
          retention-days: 14
